export const Authenticate = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};

export const Groups = {
  GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS'
};
