export const Authenticate = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS'
};

export const Groups = {
  GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS'
};

export const Messages = {
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS'
};
