language: node_js
node_js:
    - "8"
env:
  global:
    - DB_HOST=localhost
    - DB_NAME=travis_ci_test
    - DB_USER=postgres
    - DB_PORT=5432
    - DB_PASS=
    - SESS_SECRET=dui8w9837@##&
    - NODE_ENV=test
    - PORT=5000
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm run test